### ISSUE TITLE
Double-sided flag is not working

### ISSUE THREAD

**Issue by Petrosyuk** [postgrid/postgrid-python#1]
There appears to be a bug with mapping snake case kwars to came case [here](https://github.com/postgrid/postgrid-python/blob/939ab4f0ae7f07ce7d265f793b933c927ed2edef/postgrid/__init__.py#L83). This results in double_sided boolean inputs to be ignored since the API endpoint is expect doubleSided field instead of doubleSIded.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/24464919/171932182-0dfa47cf-2090-458e-8a52-46a2d018e01c.png">

**Comment by Petrosyuk** [comment]
More precisely, the bug is [here](https://github.com/postgrid/postgrid-python/blob/939ab4f0ae7f07ce7d265f793b933c927ed2edef/postgrid/__init__.py#L25) where ID (part of the KNOWN_ABBREVS) is found in double_`si`ded

**Comment by goodpaul6** [comment]
@Petrosyuk thanks! We'll get started on a fix immediately

**Comment by goodpaul6** [comment]
Hi @Petrosyuk, the fix for this has been shipped in version 1.0.6 of the package on PyPI.

Thanks again 👍
